apiVersion: v1
kind: Service
metadata:
  name: simple-api
spec:
  selector:
    app: simpleApi
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080        # cluster
      targetPort: 8080  # container
